from __future__ import annotations
import json
import os
import sys
from pathlib import Path
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / 'mpls_results'


def load_json(path: Path):
    return json.loads(path.read_text(encoding='utf-8'))


def is_result_payload(obj: object) -> bool:
    if not isinstance(obj, dict):
        return False
    report_type = str(obj.get('report_type', '')).lower()
    if 'design' in report_type:
        return False
    # Real output generated by runner.py always has timestamp and at least one
    # result/proof/control-plane field.
    if not obj.get('timestamp'):
        return False
    data_keys = ('ping', 'tcp', 'udp', 'load', 'intra', 'requirement_proofs', 'mpls_health', 'connectivity')
    for key in data_keys:
        value = obj.get(key)
        if isinstance(value, list) and len(value) > 0:
            return True
        if isinstance(value, dict) and len(value) > 0:
            return True
    return False


def result_candidates():
    items = []
    # Prefer the mirrors written by runner.py.
    items += [RESULTS / 'latest.json', RESULTS / 'dashboard_data.json', ROOT / 'dashboard_data.json']
    if RESULTS.exists():
        items += sorted(RESULTS.glob('*.json'), key=lambda p: p.stat().st_mtime, reverse=True)
    seen, out = set(), []
    for p in items:
        try:
            rp = p.resolve()
        except Exception:
            continue
        if not p.exists() or not p.is_file() or rp in seen:
            continue
        seen.add(rp)
        try:
            obj = load_json(p)
            if is_result_payload(obj):
                out.append(p)
        except Exception:
            continue
    return out


def all_json_files():
    items = []
    if RESULTS.exists():
        items += sorted(RESULTS.glob('*.json'), key=lambda p: p.stat().st_mtime, reverse=True)
    items += [ROOT / 'dashboard_data.json', ROOT / 'dashboard_data_sample.json', ROOT / 'network_design.json']
    seen, out = set(), []
    for p in items:
        try:
            rp = p.resolve()
        except Exception:
            continue
        if p.exists() and p.is_file() and rp not in seen:
            out.append(p); seen.add(rp)
    return out


def send_json(h, obj, status=200):
    body = json.dumps(obj, indent=2, ensure_ascii=False).encode('utf-8')
    h.send_response(status)
    h.send_header('Content-Type', 'application/json; charset=utf-8')
    h.send_header('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
    h.send_header('Pragma', 'no-cache')
    h.send_header('Content-Length', str(len(body)))
    h.end_headers()
    h.wfile.write(body)


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def do_GET(self):
        path = urlparse(self.path).path
        if path in ('/', '/index.html'):
            self.path = '/mpls_dashboard_tool.html'
            return super().do_GET()
        if path == '/api/latest':
            files = result_candidates()
            if not files:
                return send_json(self, {
                    'error': 'No result JSON found. Run runquick, runall, or json in Mininet first.',
                    'root': str(ROOT),
                    'expected': 'mpls_results/latest.json',
                    'known_files': [str(p.relative_to(ROOT)) for p in all_json_files()],
                }, 404)
            p = files[0]
            obj = load_json(p)
            obj['_served_from'] = str(p.relative_to(ROOT))
            obj['_served_mtime'] = p.stat().st_mtime
            return send_json(self, obj)
        if path == '/api/design':
            p = ROOT / 'network_design.json'
            if p.exists():
                obj = load_json(p)
                obj['_served_from'] = str(p.relative_to(ROOT))
                return send_json(self, obj)
            return send_json(self, {'error': 'network_design.json not found'}, 404)
        if path == '/api/files':
            rows = []
            for p in all_json_files():
                try:
                    obj = load_json(p)
                    rows.append({
                        'file': str(p.relative_to(ROOT)),
                        'mtime': p.stat().st_mtime,
                        'report_type': obj.get('report_type'),
                        'timestamp': obj.get('timestamp'),
                        'valid_result': is_result_payload(obj),
                    })
                except Exception as exc:
                    rows.append({'file': str(p.relative_to(ROOT)), 'error': str(exc), 'valid_result': False})
            return send_json(self, {'root': str(ROOT), 'files': rows, 'latest_candidates': [str(p.relative_to(ROOT)) for p in result_candidates()]})
        return super().do_GET()


class ReusableServer(ThreadingHTTPServer):
    allow_reuse_address = True


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1].isdigit() else 8000
    os.chdir(ROOT)
    print(f'Serving dashboard at: http://127.0.0.1:{port}/mpls_dashboard_tool.html')
    print(f'Latest result endpoint: http://127.0.0.1:{port}/api/latest')
    print(f'Debug files endpoint : http://127.0.0.1:{port}/api/files')
    ReusableServer(('127.0.0.1', port), Handler).serve_forever()


if __name__ == '__main__':
    main()
